on: [push]
name: Validate Code
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Test
        run: go test -cover ./...